[[redirects]]
  from = "/*"
  to = "/docs/404.html"
  status = 404

[build]
  functions = "netlify/functions"

[[plugins]]
package = "@algolia/netlify-plugin-crawler"
  [plugins.inputs]
  pathPrefix = "/docs"
  customDomain = "example.com"
  renderJavaScript = true